# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
